### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MilanObrenovic** [Crdzbird/flowder#3]
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Unsupported operation: Functionality only available on Android
#0      MethodChannelPathProvider.getExternalStoragePath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:55:7)
#1      getExternalStorageDirectory (package:path_provider/path_provider.dart:155:40)
#2      _ChatScreenState._buildDocumentMedia.<anonymous closure> (package:txt_vision/screens/chat_screen.dart:697:37)
#3      _ChatScreenState._buildDocumentMedia.<anonymous closure> (package:txt_vision/screens/chat_screen.dart:691:22)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#17     _rootRunUnary (dart:async/zone.dart:1370:13)
#18     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#20     _invoke1 (dart:ui/hooks.dart:182:10)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

**Comment by Crdzbird** [comment]
Hello @milanobrenovic, sorry for the long time of waiting... I check the issue that you mention and the problem
>MethodChannelPathProvider.getExternalStoragePath

is due to the use of `ExternalStorage` on an IOS Device, there are 2 solutions to that.

1. Use `getTemporaryDirectory()` instead of the `getExternalStorageDirectory()`
2. Use a conditional and check if android then `getExternalStorageDirectory()` if IOS `getLibraryDirectory()` 

Im gonna close this issue due be an error outside the scope of `Flowder`
